/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthResponseDto {
  accessToken?: string;
  refreshToken?: string;
  role?: 'CLIENTE' | 'ADMIN' | 'SUPERVISOR';
}
