/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Vehiculo } from '../models/vehiculo';
export interface Orden {
  activa?: boolean;
  fechaOrden?: string;
  id?: number;
  tipo?: 'MANTENIMIENTO' | 'PINTURA' | 'REPARACION' | 'REVISION';
  vehiculo?: Vehiculo;
}
