/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrdenDto {
  activa?: boolean;
  fechaOrden?: string;
  id?: number;
  idVehiculo?: number;
  tipo?: 'MANTENIMIENTO' | 'PINTURA' | 'REPARACION' | 'REVISION';
}
