/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsuarioResponseDto {
  idUsuario?: number;
  nombreCompleto?: string;
  role?: 'CLIENTE' | 'ADMIN' | 'SUPERVISOR';
  username?: string;
}
