/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Orden } from '../models/orden';
export interface Vehiculo {
  id?: number;
  marca?: string;
  modelo?: string;
  ordenes?: Array<Orden>;
  placa?: string;
}
