/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Vehiculo } from '../../models/vehiculo';

export interface ActualizarVehiculo$Params {
  id_vehiculo: number;
      body: Vehiculo
}

export function actualizarVehiculo(http: HttpClient, rootUrl: string, params: ActualizarVehiculo$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, actualizarVehiculo.PATH, 'put');
  if (params) {
    rb.path('id_vehiculo', params.id_vehiculo, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

actualizarVehiculo.PATH = '/vehiculo/{id_vehiculo}';
