/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthRequestDto } from './models/auth-request-dto';
export type { AuthResponseDto } from './models/auth-response-dto';
export type { GrantedAuthority } from './models/granted-authority';
export type { Orden } from './models/orden';
export type { OrdenDto } from './models/orden-dto';
export type { Usuario } from './models/usuario';
export type { UsuarioResponseDto } from './models/usuario-response-dto';
export type { Vehiculo } from './models/vehiculo';
export type { VehiculoDto } from './models/vehiculo-dto';
