/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { VehiculoControllerService } from './services/vehiculo-controller.service';
export { OrdenControllerService } from './services/orden-controller.service';
export { AuthenticationControllerService } from './services/authentication-controller.service';
