/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Usuario } from '../../models/usuario';
import { UsuarioResponseDto } from '../../models/usuario-response-dto';

export interface AddNewUser$Params {
      body: Usuario
}

export function addNewUser(http: HttpClient, rootUrl: string, params: AddNewUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioResponseDto>> {
  const rb = new RequestBuilder(rootUrl, addNewUser.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioResponseDto>;
    })
  );
}

addNewUser.PATH = '/auth/register';
